//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalTun.WCF.WCFServiceHost.Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_WCF_Lab1_SalesTrx
    {
        public long TrsSysId { get; set; }
        public System.DateTime TrxDateTime { get; set; }
        public long CustId { get; set; }
        public long ProdSysId { get; set; }
        public short Qnt { get; set; }
    }
}
