//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalTun.WCF.WCFServiceHost.Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_WCF_Lab1_Products
    {
        public long ProdSysId { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
        public double Price { get; set; }
        public string Currency { get; set; }
        public bool IsActive { get; set; }
    }
}
