// LMSPatternsChart.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (LMSPatternsChart.tlb) that will become a resource in
// LMSPatternsChart.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(DC599246-ED72-45B2-B7A4-34C0643688BE), version(1.0),
  helpfile("LMSPatternsChart.hlp"),
  helpstring("LMSPatternsChart ActiveX Control module"),
  control ]
library LMSPatternsChartLib
{
	importlib(STDOLE_TLB);

	//  Primary dispatch interface for CLMSPatternsChartCtrl

	[ uuid(D497676A-B978-4B6F-85C5-A90E5ADFE179),
	  helpstring("Dispatch interface for LMSPatternsChart Control")]
	dispinterface _DLMSPatternsChart
	{
		properties:
			[id(1) , helpstring("property ConnectionData")] BSTR ConnectionData;
		methods:
	};

	//  Event dispatch interface for CLMSPatternsChartCtrl

	[ uuid(CFF0436C-FF88-4F96-8FCD-AA7BD42540FD),
	  helpstring("Event interface for LMSPatternsChart Control") ]
	dispinterface _DLMSPatternsChartEvents
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CLMSPatternsChartCtrl

	[ uuid(00172661-82A6-4C68-8585-D54E46A07CCF),
	  helpstring("LMSPatternsChart Control"), control ]
	coclass LMSPatternsChart
	{
		[default] dispinterface _DLMSPatternsChart;
		[default, source] dispinterface _DLMSPatternsChartEvents;
	};

};
