//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Export.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Export.Plugin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        internal static string IDS_EPISODE_ELEM {
            get {
                return ResourceManager.GetString("IDS_EPISODE_ELEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove episode {0} from Episodes list.
        /// </summary>
        internal static string IDS_EPISODE_REMOVE_FAILED {
            get {
                return ResourceManager.GetString("IDS_EPISODE_REMOVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0} successfully removed from Episodes list.
        /// </summary>
        internal static string IDS_EPISODE_REMOVE_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_EPISODE_REMOVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpisodeStatus.
        /// </summary>
        internal static string IDS_EPISODE_STATUS_ATTR {
            get {
                return ResourceManager.GetString("IDS_EPISODE_STATUS_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportPluginLaborer.
        /// </summary>
        internal static string IDS_EXPORT_PLUGIN_LABORER {
            get {
                return ResourceManager.GetString("IDS_EXPORT_PLUGIN_LABORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotherID.
        /// </summary>
        internal static string IDS_MOTHER_ID_ATTR {
            get {
                return ResourceManager.GetString("IDS_MOTHER_ID_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove Mother ID {0} from Mothers list.
        /// </summary>
        internal static string IDS_MOTHER_ID_REMOVE_FAILED {
            get {
                return ResourceManager.GetString("IDS_MOTHER_ID_REMOVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother ID {0} successfully removed from Mothers list.
        /// </summary>
        internal static string IDS_MOTHER_ID_REMOVE_SUCCESS {
            get {
                return ResourceManager.GetString("IDS_MOTHER_ID_REMOVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiples.
        /// </summary>
        internal static string IDS_MULTIPLES_ELEM {
            get {
                return ResourceManager.GetString("IDS_MULTIPLES_ELEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string IDS_PATIENT_ELEM {
            get {
                return ResourceManager.GetString("IDS_PATIENT_ELEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientUniqueId.
        /// </summary>
        internal static string IDS_PATIENT_UNIQUE_ID_ATTR {
            get {
                return ResourceManager.GetString("IDS_PATIENT_UNIQUE_ID_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sibling.
        /// </summary>
        internal static string IDS_SIBLING_ELEM {
            get {
                return ResourceManager.GetString("IDS_SIBLING_ELEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string IDS_VISIT_KEY_ATTR {
            get {
                return ResourceManager.GetString("IDS_VISIT_KEY_ATTR", resourceCulture);
            }
        }
    }
}
