//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalTun.WCF.WebClient.SalesSrvRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entSalesTrx", Namespace="http://schemas.datacontract.org/2004/07/TalTun.WCF.WCFServiceHost.Platform")]
    [System.SerializableAttribute()]
    public partial class entSalesTrx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CustIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProdCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProdPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProdSysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TrsSysIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TrxDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustId {
            get {
                return this.CustIdField;
            }
            set {
                if ((this.CustIdField.Equals(value) != true)) {
                    this.CustIdField = value;
                    this.RaisePropertyChanged("CustId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProdCurrency {
            get {
                return this.ProdCurrencyField;
            }
            set {
                if ((this.ProdCurrencyField.Equals(value) != true)) {
                    this.ProdCurrencyField = value;
                    this.RaisePropertyChanged("ProdCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdImg {
            get {
                return this.ProdImgField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdImgField, value) != true)) {
                    this.ProdImgField = value;
                    this.RaisePropertyChanged("ProdImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdName {
            get {
                return this.ProdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdNameField, value) != true)) {
                    this.ProdNameField = value;
                    this.RaisePropertyChanged("ProdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProdPrice {
            get {
                return this.ProdPriceField;
            }
            set {
                if ((this.ProdPriceField.Equals(value) != true)) {
                    this.ProdPriceField = value;
                    this.RaisePropertyChanged("ProdPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProdSysId {
            get {
                return this.ProdSysIdField;
            }
            set {
                if ((this.ProdSysIdField.Equals(value) != true)) {
                    this.ProdSysIdField = value;
                    this.RaisePropertyChanged("ProdSysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qnt {
            get {
                return this.QntField;
            }
            set {
                if ((this.QntField.Equals(value) != true)) {
                    this.QntField = value;
                    this.RaisePropertyChanged("Qnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TrsSysId {
            get {
                return this.TrsSysIdField;
            }
            set {
                if ((this.TrsSysIdField.Equals(value) != true)) {
                    this.TrsSysIdField = value;
                    this.RaisePropertyChanged("TrsSysId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TrxDateTime {
            get {
                return this.TrxDateTimeField;
            }
            set {
                if ((this.TrxDateTimeField.Equals(value) != true)) {
                    this.TrxDateTimeField = value;
                    this.RaisePropertyChanged("TrxDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesSrvRef.ISalesDataSrv")]
    public interface ISalesDataSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesDataSrv/GetSalesTrx", ReplyAction="http://tempuri.org/ISalesDataSrv/GetSalesTrxResponse")]
        TalTun.WCF.WebClient.SalesSrvRef.entSalesTrx[] GetSalesTrx();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesDataSrv/GetSalesTrx", ReplyAction="http://tempuri.org/ISalesDataSrv/GetSalesTrxResponse")]
        System.Threading.Tasks.Task<TalTun.WCF.WebClient.SalesSrvRef.entSalesTrx[]> GetSalesTrxAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesDataSrvChannel : TalTun.WCF.WebClient.SalesSrvRef.ISalesDataSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesDataSrvClient : System.ServiceModel.ClientBase<TalTun.WCF.WebClient.SalesSrvRef.ISalesDataSrv>, TalTun.WCF.WebClient.SalesSrvRef.ISalesDataSrv {
        
        public SalesDataSrvClient() {
        }
        
        public SalesDataSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesDataSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDataSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesDataSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TalTun.WCF.WebClient.SalesSrvRef.entSalesTrx[] GetSalesTrx() {
            return base.Channel.GetSalesTrx();
        }
        
        public System.Threading.Tasks.Task<TalTun.WCF.WebClient.SalesSrvRef.entSalesTrx[]> GetSalesTrxAsync() {
            return base.Channel.GetSalesTrxAsync();
        }
    }
}
