<?xml version="1.0" encoding="utf-8"?>
<Database Name="TEST-RDPAT" Class="PatternsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=vs2005;Initial Catalog=TEST-RDPAT;Persist Security Info=True;User ID=sa" SettingsObjectName="PeriGen.Patterns.Research.SQLHelper.Properties.Settings" SettingsPropertyName="PatternsDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="UserActions">
    <Type Name="UserAction">
      <Column Name="ActionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArtifactId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PerformTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Patient_UserAction" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Artifacts">
    <Type Name="Artifact">
      <Column Name="ArtifactId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Y1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Y2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="BaselineVariability" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="PeakTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PeakValue" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Confidence" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Repair" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Height" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IsNonInterpretable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DecelerationCategory" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NonReassuringFeatures" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ContractionStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Patient_Artifact" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Tracings">
    <Type Name="Tracing">
      <Column Name="TracingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SignalHR1" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SignalUP" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Patient_Tracing" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Patients">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientKey" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Patient_UserAction" Member="UserActions" ThisKey="PatientId" OtherKey="PatientId" Type="UserAction" />
      <Association Name="Patient_Artifact" Member="Artifacts" ThisKey="PatientId" OtherKey="PatientId" Type="Artifact" />
      <Association Name="Patient_Tracing" Member="Tracings" ThisKey="PatientId" OtherKey="PatientId" Type="Tracing" />
    </Type>
  </Table>
</Database>