//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatternsAddOnManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatternsAddOnManager.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        internal static string IDS_ACCELERATION {
            get {
                return ResourceManager.GetString("IDS_ACCELERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biphasic.
        /// </summary>
        internal static string IDS_ATYP_CHAR_BIPHASIC {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_BIPHASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LossRise.
        /// </summary>
        internal static string IDS_ATYP_CHAR_LOSS_RISE {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_LOSS_RISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LossVariability.
        /// </summary>
        internal static string IDS_ATYP_CHAR_LOSS_VAR {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_LOSS_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerBaseline.
        /// </summary>
        internal static string IDS_ATYP_CHAR_LOWER_BL {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_LOWER_BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string IDS_ATYP_CHAR_NONE {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prolonged.
        /// </summary>
        internal static string IDS_ATYP_CHAR_PROLONGED {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_PROLONGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProlongedSecondRise.
        /// </summary>
        internal static string IDS_ATYP_CHAR_PROLONGED_SEC_RISE {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_PROLONGED_SEC_RISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixties.
        /// </summary>
        internal static string IDS_ATYP_CHAR_SIXTIES {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_SIXTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlowReturn.
        /// </summary>
        internal static string IDS_ATYP_CHAR_SLOW_RET {
            get {
                return ResourceManager.GetString("IDS_ATYP_CHAR_SLOW_RET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        internal static string IDS_BASELINE {
            get {
                return ResourceManager.GetString("IDS_BASELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        internal static string IDS_CONTRACTION {
            get {
                return ResourceManager.GetString("IDS_CONTRACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early.
        /// </summary>
        internal static string IDS_DECEL_CAT_EARLY {
            get {
                return ResourceManager.GetString("IDS_DECEL_CAT_EARLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string IDS_DECEL_CAT_LATE {
            get {
                return ResourceManager.GetString("IDS_DECEL_CAT_LATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonAssociated.
        /// </summary>
        internal static string IDS_DECEL_CAT_NON_ASSOC {
            get {
                return ResourceManager.GetString("IDS_DECEL_CAT_NON_ASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string IDS_DECEL_CAT_NONE {
            get {
                return ResourceManager.GetString("IDS_DECEL_CAT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string IDS_DECEL_CAT_VARIABLE {
            get {
                return ResourceManager.GetString("IDS_DECEL_CAT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        internal static string IDS_DECELERATION {
            get {
                return ResourceManager.GetString("IDS_DECELERATION", resourceCulture);
            }
        }
    }
}
