//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Patterns Application.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_PatternsApplicaTYPE         129
#define IDB_BITMAP1                     146
#define patient_view_restore_contraction 147
#define patient_view_restore_event 148
#define log_in_dlg_invalid_password_username 149
#define log_in_dlg_invalid_password_username_title 150
#define IDD_LOGIN                       151
#define no_view_permission_main_view    151
#define main_view_no_view_permission    151
#define patient_view_delete_event       152
#define IDS_STRING153                   153
#define about_dlg_address_group         153
#define about_dlg_company_address       154
#define about_dlg_copyright             155
#define about_dlg_email                 156
#define about_dlg_internet              157
#define about_dlg_fax                   158
#define about_dlg_product_information_group 159
#define about_dlg_technical             160
#define about_dlg_telephone             161
#define about_dlg_title                 162
#define about_dlg_support_group         163
#define about_dlg_contact_group         163
#define about_dlg_technical_phone_number 164
#define about_dlg_main_phone_numbers    165
#define about_dlg_fax_number            166
#define about_dlg_build                 167
#define about_dlg_version               168
#define about_dlg_internet_address      169
#define about_dlg_email_address         170
#define patient_view_no_patient_selected 171
#define patterns_application_can_not_launch 172
#define about_dlg_CE_text               173
#define patient_view_delete_contraction 173
#define intent_to_use_text              174
#define splash_dlg_loading              175
#define application_lms_title           177
#define IDB_SPLASH                      179
#define application_lms_help            179
#define IDS_PLEASE_WAIT                 180
#define IDD_SPLASH                      181
#define mandatory_fields_missing_for_admit 181
#define invalid_edd_admit               182
#define missing_proper_ADT_permissions  183
#define need_to_select_a_patient        184
#define missing_bed_transfer            185
#define function_not_supported          186
#define confirm_active_tracing_transfer 186
#define confirm_active_tracing_discharge 187
#define mandatory_fields_missing_for_modify 188
#define confirm_discharge               189
#define patient_view_accept_event       190
#define IDD_ADMIT_PATIENT               191
#define invalid_dob_range               191
#define invalid_characters_in_patient_id 192
#define IDD_DISCHARGE_PATIENT           193
#define request_activation_text         193
#define IDD_TRANSFER_PATIENT            194
#define retrospective_disclaimer        194
#define IDD_PATIENT_RECORD              195
#define IDB_BITMAP2                     199
#define IDB_CALENDAR                    201
#define IDB_CE_LOGO                     202
#define IDB_SPLASH_RETROSPECTIVE        203
#define IDD_LICENSE                     204
#define IDD_REQUEST_LICENSE             204
#define IDD_DIALOG_NO_LICENSE           205
#define IDD_DIALOG_ENTER_LICENSE        206
#define application_retrospective_help  207
#define IDD_DIALOG1                     208
#define IDD_PROCESSING                  208
#define IDSENDEMAIL                     209
#define IDRETURNTOCALM                  210
#define IDCOPYCLIPBOARD                 211
#define IDD_DIALOG_DISCLAIMER           212
#define IDD_PLEASE_WAIT                 213
#define IDD_WELCOME_SCREEN              214
#define IDB_BITMAP4                     216
#define IDB_WELCOME                     216
#define IDD_DIALOG_AUTOUPDATE           217
#define about_dlg_support_inquries      218
#define about_dlg_technical_mail		219
#define about_dlg_technical_mail_addr	220
#define IDC_COMPUTE                     1000
#define IDC_SHOW_DATA                   1001
#define IDC_INTERNET_ADDRESS            1004
#define IDC_NAME                        1005
#define IDC_EMAIL_ADDRESS               1005
#define IDC_PASSWORD                    1006
#define IDC_PASSWORD2                   1007
#define IDLOGIN                         1008
#define IDC_MESSAGE                     1009
#define IDC_PASSWORD3                   1009
#define ID_OK                           1010
#define IDC_PRODUCT_VERSION             1012
//#define IDC_PRODUCT_NAME                1012
#define IDC_COPYRIGHT                   1013
#define IDC_INFORMATION_GROUP           1014
#define IDC_ADDRESS_GROUP               1015
#define IDC_VERSION                     1016
#define IDC_COMPANY_ADDRESS             1017
#define IDC_TELEPHONE                   1018
#define IDC_TECHNICAL                   1019
#define IDC_FAX                         1020
#define IDC_INTERNET                    1021
#define IDC_EMAIL                       1022
#define IDC_SUPPORT_GROUP               1023
#define IDC_CONTACT_GROUP               1024
#define IDC_TECHNICAL_PHONE_NUMBER      1025
#define IDC_MAIN_PHONE_NUMBERS          1026
#define IDC_FAX_PHONE_NUMBER            1027
#define IDC_CE_TEXT                     1028
#define IDC_PATTERNS_HELP               1029
#define IDC_BTN_CHANGE_PASSWD           1030
#define IDC_BTN_CALENDAR                1031
#define IDC_CANCEL_UPGRADE              1032
#define IDC_SPLASH_TEXT                 1033
#define IDC_TEXT                        1034
#define IDC_PID                         1035
#define IDC_EDIT_KEY                    1036
#define IDC_EDIT_NAME                   1037
#define IDC_EDIT_DISCLAIMER             1038
#define IDC_LN                          1039
#define IDC_EDIT_ORGANIZATION           1040
#define IDC_FN                          1041
#define IDC_EDIT_SERIAL                 1042
#define IDC_PACCOUNTNO                  1043
#define IDC_EDD                         1044
#define IDC_BED                         1045
#define IDC_ADMISSIONDATE               1046
#define IDC_DISCHARGEDATE               1047
#define IDC_FETUSES                     1048
#define IDC_DOB                         1049
#define IDC_ICONBOX                     1050
#define IDC_ST_PASSWD1                  1051
#define IDC_ST_PASSWD2                  1052
#define IDC_ST_PASSWD3                  1053
#define IDC_MONTHCALENDAR_POPUP         1054
#define IDC_BTN_CALENDAR_EDD            1055
#define IDC_BTN_CALENDAR_DOB            1056
#define IDC_DOB_DTP                     1057
#define IDC_BMP                         1058
#define IDC_EDITUSERNAME                1059
#define IDC_EDITMACHINEID               1060
#define IDC_EDITKEY                     1061
#define IDC_STATUS                      1062
#define IDC_EDITORGANIZATION            1063
#define IDC_BUTTON_REQUEST_CODE         1064
#define IDC_BUTTON_ENTER_CODE           1065
#define IDC_LICENSE_GRP                 1066
#define IDC_STATIC_NAME                 1067
#define IDC_STATIC_ORGANIZATION         1068
#define IDC_STATIC_LICENSE              1069
#define IDC_BUTTON_REQUEST              1070
#define IDC_BUTTON_ACTIVATE             1071
#define IDC_EDIT_PHONE                  1072
#define IDC_STATIC_PHONE                1073
#define IDC_RADIO_DISAGREE              1074
#define IDC_RADIO_AGREE                 1075
#define IDC_STATIC_ORGANIZATION2        1076
#define IDC_RADIO1                      1077
#define IDC_WAIT_MESSAGE                1078
#define IDC_CHECK_SAMPLES               1079
#define IDC_SL_OPENFILE                 1080
#define IDC_SL_TUTORIAL                 1081
#define IDC_SL_HELP                     1082
#define IDC_SL_ABOUTPATTERNS            1083
#define IDC_SL_AUTOUPDATE               1084
#define IDC_SL_WEBSITE                  1085
#define IDC_SL_LOADSAMPLES              1086
#define IDC_LICENSE_TEXT                1087
#define IDC_PROGRESS_UPGRADE            1088
#define IDC_INTENDED_USE				1089
#define IDC_SUPPORT_AND_INQUIRIES_GROUP	1090
#define IDC_TECHNICAL_MAIL				1091
#define IDC_TECHNICAL_MAIL_ADDR			1092
#define ID_VIEW_BASELINE                32771
#define ID_DEBUG_MODE                   32774
#define ID_PATIENT_LIST                 32778
#define ID_PATIENT_LIST_ENTER           32779
#define ID_PATIENT_LIST_RETURN          32779
#define ID_DEBUG_SAVE                   32781
#define ID_HYPERSTIMULATION_VIEW_SWITCH 32783
#define ID_BEGINNING                    32785
#define ID_END                          32786
#define ID_PREVIOUS_PAGE                32787
#define ID_NEXT_PAGE                    32788
#define ID_MOVE_LEFT                    32789
#define ID_MOVE_RIGHT                   32790
#define ID_TOGGLE_DISPLAY_EVENTS        32792
#define ID_TOGGLE_DISPLAY_MINI_VIEW     32793
#define ID_DEBUG_OPEN                   32795
#define ID_VIEW_MONTEVIDEO              32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
